# Generated by Django 6.0.5 on 2026-06-02 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_add_skill_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Achievement', 'verbose_name_plural': 'Achievements'},
        ),
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['-issue_date', 'certificate_name'], 'verbose_name': 'Certification', 'verbose_name_plural': 'Certifications'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-completion_year', 'college_name'], 'verbose_name': 'Education', 'verbose_name_plural': 'Education'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-level', 'name'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
    ]
