# Generated by Django 6.0.5 on 2026-06-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_skill_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='cgpa',
            new_name='score_value',
        ),
        migrations.AddField(
            model_name='education',
            name='education_type',
            field=models.CharField(choices=[('SSC', 'SSC'), ('Intermediate', 'Intermediate'), ('Diploma', 'Diploma'), ('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate'), ('PhD', 'PhD'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='education',
            name='scoring_type',
            field=models.CharField(choices=[('CGPA', 'CGPA'), ('Percentage', 'Percentage')], default='CGPA', max_length=20),
        ),
    ]
