# Generated by Django 6.0.5 on 2026-06-04 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_rename_cgpa_education_score_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioViewTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('viewer_ip', models.CharField(blank=True, max_length=45)),
                ('is_recruiter', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portfolio View Log',
                'verbose_name_plural': 'Portfolio View Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
